# Basic pipeline. Will run unit tests, build and push a new docker image, then deploy on heroku

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: Executing Unit Tests
    jobs:
      - job: UnitTest
        steps:
          - bash: echo Should run unit tests here
  - stage: Dockerize
    dependsOn: Test
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Docker Image
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub connection'
            command: 'login'
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub connection'
            repository: 'achung98/covid-tracker-angular'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'
  - stage: Deploy
    dependsOn: Dockerize
    jobs:
      - job: HerokuDockerRegistry
        displayName: Push Image to Heroku Docker Registry
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - script: |
              sudo docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/$(app)/web .
              sudo docker login -u _ -p $(herokupass) registry.heroku.com
              sudo docker push registry.heroku.com/$(app)/web
              apk add --no-cache curl
              curl -X PATCH https://api.heroku.com/apps/$(app)/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer $(herokupass)" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
